management:
  server: 
    port: 8094
  endpoints: 
    web: 
      exposure: 
        include: "*" 
  endpoint: 
    health:   
      show-details: "always"

spring:
  application:
    name: PorkersPicks
  datasource:
    url: jdbc:mysql://localhost:3306/porkerspicks
    username: root
    password: norrie
    tomcat.max-wait: 20000 
    tomcat.max-active: 50 
    tomcat.max-idle: 20 
    tomcat.min-idle: 15 
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  
logging:
  config: classpath:logback-spring.xml
  file:
    name: c:/dev/logs/porkerspicks.log
  level:
    root: info
    com:
      porkerspicks: debug
    org: 
      springframework:
        security: debug
      hibernate:
          SQL:  debug

        
mail:
  from: error@porkerspicks.com
  to:   wullparker@gmail.com

debug: false